name: Sync LoonKissSurge

on:
  schedule:
    - cron: '0 8 * * *'  # 每天午夜12点执行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "Your GitHub Email"

      - name: Clone the target repository
        run: |
          git clone https://github.com/QingRex/LoonKissSurge.git
          cd LoonKissSurge
          git pull origin main  # 获取最新内容

      - name: Copy the files to current repository
        run: |
          cp -r LoonKissSurge/* .  # 将文件复制到当前仓库

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync latest changes from LoonKissSurge"
          git push origin main  # 推送到当前仓库

