name: Sync LoonKissSurge

on:
  schedule:
    - cron: '0 8 * * *'  # 每天午夜8点执行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Lincorn"
          git config --global user.email "lemonas@example.com"

      - name: Clone the target repository
        run: |
          git clone https://github.com/QingRex/LoonKissSurge.git
          cd LoonKissSurge
          git pull origin main  # 获取最新内容

      - name: Copy the files to current repository
        run: |
          cp -r LoonKissSurge/* .
          ls -la  # 检查当前目录内容

      - name: Commit changes
        run: |
          git add -A  # 强制添加所有变化
          git commit -m "Sync latest changes from LoonKissSurge" || echo "No changes to commit"
          git push origin main  # 推送到当前仓库
